# AUTOGENERATED! DO NOT EDIT! File to edit: ../store_sales_3.ipynb.

# %% auto 0
__all__ = ['iskaggle', 'creds', 'cred_path', 'path', 'train_df', 'test_df', 'stores_df', 'transactions_df']

# %% ../store_sales_3.ipynb 1
from fastai.tabular.all import *
from fastbook import *

from sklearn.ensemble import RandomForestRegressor

import seaborn as sns
import plotly.express as px

# %% ../store_sales_3.ipynb 2
iskaggle = os.environ.get('KAGGLE_KERNEL_RUN_TYPE', '')
creds = ''

# %% ../store_sales_3.ipynb 3
cred_path = Path('~/.kaggle/kaggle.json').expanduser()
if not cred_path.exists():
    cred_path.parent.mkdir(exist_ok=True)
    cred_path.write_text(creds)
    cred_path.chmod(0o600)

# %% ../store_sales_3.ipynb 4
path = Path('store-sales-time-series-forecasting')

# %% ../store_sales_3.ipynb 5
if not iskaggle and not path.exists():
    import zipfile, kaggle
    kaggle.api.competition_download_cli(str(path))    
    zipfile.ZipFile(f'{path}.zip').extractall(path)


# %% ../store_sales_3.ipynb 6
if iskaggle:
    path = Path('../input/store-sales-time-series-forecasting')
    ! pip install -q dataset

# %% ../store_sales_3.ipynb 8
train_df = pd.read_csv(path/'train.csv', low_memory=False)
test_df = pd.read_csv(path/'test.csv', low_memory=False)
# sub_df = pd.read_csv(path/'sample_submission.csv', low_memory=False)
stores_df = pd.read_csv(path/'stores.csv', low_memory=False)    
transactions_df = pd.read_csv(path/'transactions.csv', low_memory=False).sort_values(['store_nbr', 'date'])

# %% ../store_sales_3.ipynb 10
train_df['date'] = pd.to_datetime(train_df.date)
test_df['date'] = pd.to_datetime(test_df.date)
transactions_df['date'] = pd.to_datetime(transactions_df.date)

# %% ../store_sales_3.ipynb 12
train_df.onpromotion = train_df.onpromotion.astype("float16")
train_df.sales = train_df.sales.astype("float32")
stores_df.cluster = stores_df.cluster.astype("int8")
